### ISSUE TITLE
Don't use async/await

### ISSUE THREAD

**Issue by gutenye** [fenos/graphql-thinky#3]
It needs `require('babel-polyfill')` in a vanilla node script or use `babel-node` to run it. 

It's bad to force developers use the babel-polyfill.

**Comment by fenos** [comment]
Thanks for the suggestion, appreciated. I choose to use `async` & `await` because it allowed me to write more clean code. If it is something that developers doesn't like as you mentioned, I'll be happy to replace them with standard way.  Let's keep this open and gather feedback. I really enjoy the expressiveness of `async` & `await`

**Comment by gutenye** [comment]
Chrome 55 Beta added `async/await`, https://blog.chromium.org/2016/10/chrome-55-beta-input-handling.html

So node will have it in the near feature.
